//! The IPC contract: JSON shapes of the tagged enums, and the TypeScript bindings ts-rs writes to
//! `ui/src/generated/` while `cargo test` runs.

use std::fs;
use std::path::{Path, PathBuf};

use lectern_core::ipc::{
    DocPayload, EditorPref, FollowResult, Measure, OpenError, OpenErrorKind, OpenResult,
    RecentEntry, RootState, SettingsPatch, StartupPayload, UserOpen,
};
use lectern_core::library::MARKDOWN_EXTENSIONS;
use lectern_core::review::anchor::AnchorState;
use lectern_core::review::ops::{NewAnchor, ReviewOp, StatusChange};
use lectern_core::review::{ClaudeKind, CommentStatus, EntryAuthor};
use serde_json::json;
use ts_rs::{Config, TS};

fn generated_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../ui/src/generated")
}

fn decl<T: TS>() -> String {
    T::decl(&Config::from_env())
}

#[test]
fn export_config_comes_from_cargo_config() {
    let dir = std::env::var("TS_RS_EXPORT_DIR")
        .expect("TS_RS_EXPORT_DIR unset: run cargo inside the repo so .cargo/config.toml applies");
    assert_eq!(
        fs::canonicalize(dir).unwrap(),
        fs::canonicalize(generated_dir()).unwrap()
    );
    assert_eq!(std::env::var("TS_RS_LARGE_INT").as_deref(), Ok("number"));
}

#[test]
fn ts_bindings_exported() {
    let dir = generated_dir();
    for name in [
        "Settings",
        "SettingsPatch",
        "Measure",
        "EditorPref",
        "OpenResult",
        "DocPayload",
        "StartupPayload",
        "LibraryPayload",
        "RootState",
        "FollowResult",
        "TreeNode",
        "OutlineItem",
        "Frontmatter",
        "PropValue",
        "UserOpen",
        "CommentStatus",
        "ClaudeKind",
        "EntryAuthor",
        "AnchorState",
        "NewAnchor",
        "ReviewOp",
        "StatusChange",
        "ReviewPayload",
        "CommentView",
        "EntryView",
        "UnreadableView",
    ] {
        assert!(
            dir.join(format!("{name}.ts")).is_file(),
            "{name}.ts missing from {}",
            dir.display()
        );
    }
    for entry in fs::read_dir(&dir).unwrap() {
        let path = entry.unwrap().path();
        let text = fs::read_to_string(&path).unwrap();
        assert!(
            !text.contains("bigint"),
            "{} uses bigint, which JSON cannot carry",
            path.display()
        );
    }
}

/// The Markdown extensions, for the UI's file picker, written next to the ts-rs bindings so the
/// list lives in one place. Written only when it changed, so the file keeps its timestamp.
#[test]
fn markdown_extensions_exported() {
    let list = MARKDOWN_EXTENSIONS
        .iter()
        .map(|ext| format!("\"{ext}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let ts = format!(
        "// Generated from `lectern_core::library::MARKDOWN_EXTENSIONS` by `cargo test -p lectern-core`. Do not edit this file manually.\n\n\
         /** The extensions of the files Lectern treats as Markdown notes. */\n\
         export const MARKDOWN_EXTENSIONS: readonly string[] = [{list}];\n"
    );
    let path = generated_dir().join("markdown-extensions.ts");
    if fs::read_to_string(&path).ok().as_deref() != Some(ts.as_str()) {
        fs::write(&path, &ts).unwrap();
    }
    assert!(ts.contains(r#"["md", "markdown", "mdown", "mkd"]"#), "{ts}");
}

#[test]
fn ts_unions_follow_the_serde_tags() {
    assert_eq!(decl::<Measure>(), r#"type Measure = "full" | number;"#);
    assert_eq!(
        decl::<EditorPref>(),
        r#"type EditorPref = { "mode": "auto" } | { "mode": "custom", command: string, };"#
    );
    assert_eq!(
        decl::<OpenResult>(),
        r#"type OpenResult = { "status": "ok", doc: DocPayload, } | { "status": "err", error: OpenError, };"#
    );
    assert_eq!(
        decl::<RootState>(),
        r#"type RootState = { "state": "scanning" } | { "state": "ready" } | { "state": "unavailable", reason: string, };"#
    );
    assert_eq!(
        decl::<FollowResult>(),
        r#"type FollowResult = { "action": "openDoc", path: string, anchor: string | null, line: number | null, } | { "action": "opened" } | { "action": "notFound", message: string, };"#
    );
    assert_eq!(
        decl::<CommentStatus>(),
        r#"type CommentStatus = "open" | "replied" | "question" | "pushback" | "resolved" | "dismissed";"#
    );
    assert_eq!(
        decl::<ClaudeKind>(),
        r#"type ClaudeKind = "reply" | "question" | "pushback" | "resolved";"#
    );
    assert_eq!(
        decl::<EntryAuthor>(),
        r#"type EntryAuthor = "you" | "agent";"#
    );
    assert_eq!(
        decl::<AnchorState>(),
        r#"type AnchorState = "anchored" | "moved" | "detached";"#
    );
    assert_eq!(
        decl::<StatusChange>(),
        r#"type StatusChange = "resolve" | "reopen" | "dismiss";"#
    );
    assert_eq!(
        decl::<NewAnchor>(),
        concat!(
            "type NewAnchor = { startLine: number, endLine: number, quote: string, \n",
            "/**\n",
            " * Up to `CONTEXT_CHARS` (32) characters of the note's visible text just before a selection,\n",
            " * which tell apart a phrase found more than once in its lines; empty for a whole block.\n",
            " */\n",
            "prefix: string, };",
        )
    );
    assert_eq!(
        decl::<ReviewOp>(),
        concat!(
            r#"type ReviewOp = { "op": "add", anchor: NewAnchor, text: string, } | "#,
            r#"{ "op": "reply", id: number, text: string, } | "#,
            r#"{ "op": "setStatus", id: number, change: StatusChange, } | "#,
            r#"{ "op": "reattach", id: number, anchor: NewAnchor, } | "#,
            r#"{ "op": "edit", id: number, entry: number, text: string, };"#,
        )
    );
}

#[test]
fn review_ops_are_tagged_by_op() {
    let op: ReviewOp =
        serde_json::from_value(json!({"op": "setStatus", "id": 3, "change": "resolve"})).unwrap();
    assert_eq!(
        op,
        ReviewOp::SetStatus {
            id: 3,
            change: StatusChange::Resolve
        }
    );
    let add = ReviewOp::Add {
        anchor: NewAnchor {
            start_line: 4,
            end_line: 6,
            quote: "batches of at most 50".to_owned(),
            prefix: String::new(),
        },
        text: "Why 50?".to_owned(),
    };
    assert_eq!(
        serde_json::to_value(&add).unwrap(),
        json!({"op": "add", "anchor": {"startLine": 4, "endLine": 6, "quote": "batches of at most 50", "prefix": ""}, "text": "Why 50?"})
    );
    // An anchor sent without a prefix has an empty one.
    let without: ReviewOp = serde_json::from_value(
        json!({"op": "add", "anchor": {"startLine": 4, "endLine": 6, "quote": "batches of at most 50"}, "text": "Why 50?"}),
    )
    .unwrap();
    assert_eq!(without, add);
}

#[test]
fn user_open_may_open_nothing() {
    assert_eq!(
        decl::<UserOpen>(),
        r#"type UserOpen = { doc: OpenResult | null, library: LibraryPayload, };"#
    );
}

#[test]
fn ts_numbers_are_numbers_and_patches_are_partial() {
    assert!(decl::<DocPayload>().contains("mtimeMs: number,"));
    assert!(decl::<RecentEntry>().contains("openedMs: number,"));
    assert!(decl::<SettingsPatch>().contains("fontSize?: number | null,"));
}

#[test]
fn open_result_is_tagged_by_status() {
    let r = OpenResult::Err {
        error: OpenError {
            kind: OpenErrorKind::NotFound,
            message: "gone".to_owned(),
            path: "C:\\n\\a.md".to_owned(),
        },
    };
    assert_eq!(
        serde_json::to_value(&r).unwrap(),
        json!({"status": "err", "error": {"kind": "notFound", "message": "gone", "path": "C:\\n\\a.md"}})
    );
}

#[test]
fn root_state_is_tagged_by_state() {
    assert_eq!(
        serde_json::to_value(RootState::Scanning).unwrap(),
        json!({"state": "scanning"})
    );
    assert_eq!(
        serde_json::to_value(RootState::Unavailable {
            reason: "timed out".to_owned()
        })
        .unwrap(),
        json!({"state": "unavailable", "reason": "timed out"})
    );
}

#[test]
fn follow_result_is_tagged_by_action() {
    assert_eq!(
        serde_json::to_value(FollowResult::OpenDoc {
            path: "C:\\n\\b.md".to_owned(),
            anchor: Some("intro".to_owned()),
            line: None,
        })
        .unwrap(),
        json!({"action": "openDoc", "path": "C:\\n\\b.md", "anchor": "intro", "line": null})
    );
    assert_eq!(
        serde_json::to_value(FollowResult::Opened).unwrap(),
        json!({"action": "opened"})
    );
}

#[test]
fn startup_payload_carries_a_notice() {
    let j = serde_json::to_value(StartupPayload {
        settings: Default::default(),
        library: lectern_core::ipc::LibraryPayload { roots: vec![] },
        recent: vec![],
        initial: None,
        version: "0.1.0".to_owned(),
        portable: false,
        startup_notice: Some("Settings were reset".to_owned()),
    })
    .unwrap();
    assert_eq!(j["startupNotice"], "Settings were reset");
    assert!(j["initial"].is_null());
    assert_eq!(j["settings"]["measure"], 100);
}
